version: 0.2
env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
    VERSION: "1.0"
    IMAGE_REPO_NAME: "my-xyz-project"
    AWS_ACCOUNT_ID: "123456789"
    AWS_DEFAULT_REGION: "us-east-1"
phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo Entered the install phase...
      - echo Logging in to Amazon ECR... 
      - $(aws ecr get-login --no-include-email --region     $AWS_DEFAULT_REGION)
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image..
      - mvn -X package xyz
      - docker build -t $IMAGE_REPO_NAME:$VERSION .
      - printf '{"ImageURI":"%s"}'  $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$VERSION  > /imageDetail.json
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$VERSION
artifacts:
    files: /imageDetail.json
    discard-paths: yes
